#!/usr/bin/env python
"""Rank probe cells by plateau-faceting severity — automate seed selection.

The Pixal3D shape decode is seed-dependent: most seeds produce smooth
surfaces broken into plateau-scale tilted patches (~19 deg) that read as
hard facets on glossy materials; 2-3 seeds out of 20 come out clean.
Production answer (Spenser, 2026-06-11): don't post-process the geometry —
run several seeds and pick a clean one. This script automates the picking.

Metric: band-pass energy of the luminance image at the plateau scale
(Gaussian difference, sigmas scaled to image size), measured on an eroded
foreground mask. Plateau facets put energy exactly in that band; clean
decodes don't. Lower score = smoother surfaces. The score is comparable
ACROSS cells of the same asset (same framing/material), NOT across assets.

USAGE:
    # one probe dir -> ranked table + seed_ranking.md next to the cells
    python scripts/rank_seeds.py <dataset>/probe

    # all probe dirs under a datasets root
    python scripts/rank_seeds.py <hotfolder>/datasets --all

CPU-only (PIL + numpy), safe to run while the daemon owns the GPU.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter

CELL_RE = re.compile(r"^(\d+)_T(\d+)_([a-z]+)_seed(\d+)\.png$")

# Band-pass sigmas at reference width 3000 px (probe production resolution):
# plateau wavelength is ~5-15% of the subject -> ~100-300 px features.
SIGMA_LO_REF = 18.0    # passes plateau-scale structure
SIGMA_HI_REF = 75.0    # removes global shading gradients
REF_WIDTH = 3000.0
EDGE_ERODE_REF = 24    # px of silhouette to discard (rim lighting != facets)


def plateau_score(png: Path) -> float | None:
    """Band-pass luminance energy on the eroded foreground. Lower = cleaner."""
    img = Image.open(png)
    has_alpha = img.mode in ("RGBA", "LA")
    rgb = img.convert("RGB")
    w, h = rgb.size
    scale = w / REF_WIDTH

    arr = np.asarray(rgb, dtype=np.float32) / 255.0
    lum = 0.2126 * arr[..., 0] + 0.7152 * arr[..., 1] + 0.0722 * arr[..., 2]

    if has_alpha:
        mask = np.asarray(img.getchannel("A"), dtype=np.float32) > 200
    else:                                  # polished probes are flattened
        mask = lum > 0.04                  # near-black background
    if mask.mean() < 0.005:
        return None

    erode_px = max(3, int(EDGE_ERODE_REF * scale))
    m_img = Image.fromarray((mask * 255).astype(np.uint8))
    # MinFilter kernel must be odd and >=3; chain for large radii
    k = 2 * erode_px + 1
    m_img = m_img.filter(ImageFilter.MinFilter(min(k, 31)))
    if k > 31:
        m_img = m_img.filter(ImageFilter.MinFilter(min(k - 30, 31)))
    mask = np.asarray(m_img) > 128
    if mask.sum() < 500:
        return None

    lum_img = Image.fromarray((lum * 255).astype(np.uint8))
    lo = np.asarray(lum_img.filter(
        ImageFilter.GaussianBlur(SIGMA_LO_REF * scale)), dtype=np.float32)
    hi = np.asarray(lum_img.filter(
        ImageFilter.GaussianBlur(SIGMA_HI_REF * scale)), dtype=np.float32)
    band = (lo - hi) / 255.0
    return float(np.sqrt(np.mean(band[mask] ** 2)) * 100.0)


def rank_probe_dir(probe_dir: Path, write_md: bool = True) -> list[dict]:
    cells = []
    for png in sorted(probe_dir.glob("*.png")):
        m = CELL_RE.match(png.name)
        if not m:
            continue
        score = plateau_score(png)
        if score is None:
            continue
        cells.append({
            "file": png.name,
            "view": int(m.group(1)),
            "tier": int(m.group(2)),
            "tier_name": m.group(3),
            "seed": int(m.group(4)),
            "score": score,
        })
    cells.sort(key=lambda c: c["score"])

    if cells and write_md:
        lines = [
            "# Seed ranking — plateau-faceting score",
            "",
            "Lower = smoother surfaces (less plateau-band luminance energy).",
            "Scores comparable within this asset only. Generated by rank_seeds.py.",
            "",
            "| rank | tier | seed | score | file |",
            "|------|------|------|-------|------|",
        ]
        for i, c in enumerate(cells, 1):
            lines.append(f"| {i} | T{c['tier']} {c['tier_name']} | {c['seed']} "
                         f"| {c['score']:.2f} | {c['file']} |")
        (probe_dir / "seed_ranking.md").write_text("\n".join(lines) + "\n")
    return cells


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("path", type=Path,
                   help="A probe dir, or a datasets root with --all")
    p.add_argument("--all", action="store_true",
                   help="Treat PATH as a datasets root; rank every */probe dir.")
    p.add_argument("--top", type=int, default=5,
                   help="Rows to print per asset (full table goes to "
                        "seed_ranking.md).")
    args = p.parse_args()

    dirs = (sorted(d for d in args.path.glob("*/probe") if d.is_dir())
            if args.all else [args.path])
    if not dirs:
        print(f"no probe dirs found under {args.path}")
        return 1

    for d in dirs:
        cells = rank_probe_dir(d)
        label = d.parent.name if d.name == "probe" else d.name
        if not cells:
            print(f"{label}: no scoreable cells")
            continue
        print(f"\n{label}  ({len(cells)} cells, ranking -> {d / 'seed_ranking.md'})")
        for i, c in enumerate(cells[:args.top], 1):
            print(f"  {i}. T{c['tier']} {c['tier_name']:<9} seed={c['seed']:<7} "
                  f"score={c['score']:.2f}")
        worst = cells[-1]
        print(f"  worst: T{worst['tier']} seed={worst['seed']} "
              f"score={worst['score']:.2f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
